use-conda: true
jobs: "99"
latency-wait: "200"
printshellcmds: true
keep-going: true
config:
  - "sample_sheet='config/sample_sheet.yaml'"
  - "output_dir='output'"
drmaa: " -q bio -n {threads}"
drmaa-log-dir: output/log/drmaa
