use-conda: true
jobs: "99"
latency-wait: "200"
printshellcmds: true
keep-going: true
config:
  - "sample_sheet='sample_sheet.yaml'"
  - "output_dir='out'"
drmaa: " -q bio -n {threads}"
drmaa-log-dir: out/log/drmaa
